site_name: LIBXS
site_author: Hans Pabst
copyright: Copyright (c) 2009-2026, LIBXS <a href="http://libxs.readthedocs.io/LICENSE/">Contributors</a>.
site_description: Library for specialized dense and sparse matrix operations, and deep learning primitives.
repo_url: https://github.com/hfp/libxs/
edit_uri: edit/main/documentation
site_url: https://libxs.readthedocs.io/
docs_dir: documentation

markdown_extensions:
- toc:
    permalink: True
    toc_depth: 3
    title: None
extra_css:
- style.css

theme:
    name: readthedocs
    custom_dir: .theme

hooks:
- .theme/ford_hook.py

nav:
- Overview: index.md
- Compatibility: libxs_compat.md
- Validation: libxs_valid.md
- Scripts: libxs_scripts.md
- Q&A: libxs_qna.md
- LIBXS Domains:
  - "MM: Matrix Multiplication": libxs_mm.md
  - "TPP: Tensor Processing Primitives": libxs_tpp.md
  - "DNN: Deep Neural Networks": https://libxs.readthedocs.io/#deep-learning
  - "AUX: Service Functions": libxs_aux.md
  - "PROF: Performance Profiling": libxs_prof.md
  - "TUNE: Customization": libxs_tune.md
  - "BE: Backend": libxs_be.md
- Fortran:
  - Reference: fortran/module/libxs.html
- Example Code:
  - Collection: libxs_samples.md
- Machine Learning (ML):
  - PlaidML tensor compiler: https://github.com/plaidml/plaidml
  - Extension for PyTorch: https://github.com/hfp/libxs/tree/main/samples/deeplearning/conv1dopti_layer
- Scientific (HPC):
  - CP2K: cp2k.md
  - SeisSol: https://seissol.readthedocs.io/en/latest/compilation.html#installing-libxs
  - SpECTRE: https://sxs-collaboration.github.io/spectre/installation.html
  - libCEED: https://ceed.exascaleproject.org/ceed-code/
  - Fastor: https://github.com/romeric/Fastor/wiki/9.-Using-the-LIBXS-MKL-JIT-backend
  - EDGE: https://usr.dial3343.org/en/master/chapters/install/edge.html#edge
  - PyFR: https://pyfr.readthedocs.io/en/latest/performance_tuning.html#libxs
- About:
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
