docs_dir: documentation
theme: readthedocs
theme_dir: .theme
markdown_extensions:
- toc:
    permalink: True
extra_javascript:
- search.js
extra_css:
- style.css

site_name: LIBXS
site_author: Hans Pabst
copyright: Copyright (c) 2009-2017, LIBXS <a href="http://libxs.readthedocs.io/LICENSE/">Contributors</a>.
site_description: Library targeting Intel Architecture for small, dense or sparse matrix multiplications, and small convolutions.
repo_url: https://github.com/hfp/libxs.git

pages:
- index.md
- Domains:
  - "MM: Matrix Multiplication": libxs_mm.md
  - "DNN: Deep Neural Networks": libxs_dnn.md
  - "AUX: Service Functions": libxs_aux.md
  - "PROF: Perf. Profiling": libxs_prof.md
  - "TUNE: Customization": libxs_tune.md
  - "BE: Backend": libxs_be.md
- Applications:
  - CP2K: cp2k.md
  - TensorFlow: tensorflow.md
- About:
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
