site_name: LIBXS
site_author: Hans Pabst
copyright: Copyright (c) 2009-2019, LIBXS <a href="http://libxs.readthedocs.io/LICENSE/">Contributors</a>.
site_description: Library targeting Intel Architecture for specialized dense and sparse matrix operations, and deep learning primitives.
repo_url: https://github.com/hfp/libxs/
edit_uri: edit/master/documentation
docs_dir: documentation

markdown_extensions:
- toc:
    permalink: True
    title: None
extra_css:
- style.css

theme:
    name: readthedocs
    custom_dir: .theme

nav:
- Overview: index.md
- Domains:
  - "MM: Matrix Multiplication": libxs_mm.md
  - "DNN: Deep Neural Networks": libxs_dl.md
  - "AUX: Service Functions": libxs_aux.md
  - "PROF: Performance Profiling": libxs_prof.md
  - "TUNE: Customization": libxs_tune.md
  - "BE: Backend": libxs_be.md
- Samples: libxs_samples.md
- Applications:
  - CP2K Molecular Dynamics: cp2k.md
  - GxM Deeplearning: gxm.md
  - TensorFlow: tensorflow.md
  - SeisSol: https://seissol.readthedocs.io/en/latest/compilation.html#installing-libxs
  - EDGE: http://usr.dial3343.org/en/master/chapters/install/edge.html#libxs
  - PyFR: http://pyfr.org/user_guide.php
- About:
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
